name: C# Console App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Check Code Formatting
      run: dotnet format --verify-no-changes
      continue-on-error: true # optional — you can set to false to fail if not formatted

    - name: Build Project
      run: dotnet build --no-restore --configuration Release

    - name: Run Syntax Check / Compilation Test
      run: dotnet build --no-restore --configuration Release --warnaserror

